sources:
  - name: cricket_raw
    database: data-management-2-manoj
    tables:
      - name: cricket_match_raw
      - name: players_info
      - name: stadium_coordinates
      - name: weather_info
      
  # - name: analytics
  #   database: data-management-2-manoj
  #   tables:
  #     - name: match_weather